/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateUserInput = {
  id?: string | null,
  cognitoID: string,
  identityID?: string | null,
  name: string,
  viewName?: string | null,
  description?: string | null,
  iconUrl?: string | null,
  email: string,
  _version?: number | null,
};

export type ModelUserConditionInput = {
  cognitoID?: ModelStringInput | null,
  identityID?: ModelStringInput | null,
  name?: ModelStringInput | null,
  viewName?: ModelStringInput | null,
  description?: ModelStringInput | null,
  iconUrl?: ModelStringInput | null,
  email?: ModelStringInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type UpdateUserInput = {
  id: string,
  cognitoID?: string | null,
  identityID?: string | null,
  name?: string | null,
  viewName?: string | null,
  description?: string | null,
  iconUrl?: string | null,
  email?: string | null,
  _version?: number | null,
};

export type DeleteUserInput = {
  id?: string | null,
  _version?: number | null,
};

export type CreatePostInput = {
  id?: string | null,
  title: string,
  URL?: string | null,
  tag?: string | null,
  date?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  userID: string,
  _version?: number | null,
};

export type ModelPostConditionInput = {
  title?: ModelStringInput | null,
  URL?: ModelStringInput | null,
  tag?: ModelStringInput | null,
  date?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  and?: Array< ModelPostConditionInput | null > | null,
  or?: Array< ModelPostConditionInput | null > | null,
  not?: ModelPostConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdatePostInput = {
  id: string,
  title?: string | null,
  URL?: string | null,
  tag?: string | null,
  date?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  userID?: string | null,
  _version?: number | null,
};

export type DeletePostInput = {
  id?: string | null,
  _version?: number | null,
};

export type CreateReplyInput = {
  id?: string | null,
  postID: string,
  type: string,
  content: string,
  request?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  userID: string,
  _version?: number | null,
};

export type ModelReplyConditionInput = {
  postID?: ModelIDInput | null,
  type?: ModelStringInput | null,
  content?: ModelStringInput | null,
  request?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  and?: Array< ModelReplyConditionInput | null > | null,
  or?: Array< ModelReplyConditionInput | null > | null,
  not?: ModelReplyConditionInput | null,
};

export type UpdateReplyInput = {
  id: string,
  postID?: string | null,
  type?: string | null,
  content?: string | null,
  request?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  userID?: string | null,
  _version?: number | null,
};

export type DeleteReplyInput = {
  id?: string | null,
  _version?: number | null,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  cognitoID?: ModelStringInput | null,
  identityID?: ModelStringInput | null,
  name?: ModelStringInput | null,
  viewName?: ModelStringInput | null,
  description?: ModelStringInput | null,
  iconUrl?: ModelStringInput | null,
  email?: ModelStringInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelPostFilterInput = {
  id?: ModelIDInput | null,
  title?: ModelStringInput | null,
  URL?: ModelStringInput | null,
  tag?: ModelStringInput | null,
  date?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  and?: Array< ModelPostFilterInput | null > | null,
  or?: Array< ModelPostFilterInput | null > | null,
  not?: ModelPostFilterInput | null,
};

export type ModelReplyFilterInput = {
  id?: ModelIDInput | null,
  postID?: ModelIDInput | null,
  type?: ModelStringInput | null,
  content?: ModelStringInput | null,
  request?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  and?: Array< ModelReplyFilterInput | null > | null,
  or?: Array< ModelReplyFilterInput | null > | null,
  not?: ModelReplyFilterInput | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreatePostMutationVariables = {
  input: CreatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type CreatePostMutation = {
  createPost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdatePostMutationVariables = {
  input: UpdatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type UpdatePostMutation = {
  updatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeletePostMutationVariables = {
  input: DeletePostInput,
  condition?: ModelPostConditionInput | null,
};

export type DeletePostMutation = {
  deletePost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type CreateReplyMutationVariables = {
  input: CreateReplyInput,
  condition?: ModelReplyConditionInput | null,
};

export type CreateReplyMutation = {
  createReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateReplyMutationVariables = {
  input: UpdateReplyInput,
  condition?: ModelReplyConditionInput | null,
};

export type UpdateReplyMutation = {
  updateReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteReplyMutationVariables = {
  input: DeleteReplyInput,
  condition?: ModelReplyConditionInput | null,
};

export type DeleteReplyMutation = {
  deleteReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type SyncUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncUsersQuery = {
  syncUsers:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type SyncPostsQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncPostsQuery = {
  syncPosts:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type GetPostQueryVariables = {
  id: string,
};

export type GetPostQuery = {
  getPost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListPostsQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPostsQuery = {
  listPosts:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type SyncRepliesQueryVariables = {
  filter?: ModelReplyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncRepliesQuery = {
  syncReplies:  {
    __typename: "ModelReplyConnection",
    items:  Array< {
      __typename: "Reply",
      id: string,
      postID: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null,
      type: string,
      content: string,
      request: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type GetReplyQueryVariables = {
  id: string,
};

export type GetReplyQuery = {
  getReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListReplysQueryVariables = {
  filter?: ModelReplyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListReplysQuery = {
  listReplys:  {
    __typename: "ModelReplyConnection",
    items:  Array< {
      __typename: "Reply",
      id: string,
      postID: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null,
      type: string,
      content: string,
      request: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type UserByCognitoIdQueryVariables = {
  cognitoID?: string | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type UserByCognitoIdQuery = {
  userByCognitoID:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type PostByUserIdQueryVariables = {
  userID?: string | null,
  createdAt?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type PostByUserIdQuery = {
  postByUserID:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type PostByDateQueryVariables = {
  date?: string | null,
  createdAt?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type PostByDateQuery = {
  postByDate:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type ReplyByUserIdQueryVariables = {
  userID?: string | null,
  createdAt?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelReplyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ReplyByUserIdQuery = {
  replyByUserID:  {
    __typename: "ModelReplyConnection",
    items:  Array< {
      __typename: "Reply",
      id: string,
      postID: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null,
      type: string,
      content: string,
      request: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type ReplyByPostIdQueryVariables = {
  postID?: string | null,
  createdAt?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelReplyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ReplyByPostIdQuery = {
  replyByPostID:  {
    __typename: "ModelReplyConnection",
    items:  Array< {
      __typename: "Reply",
      id: string,
      postID: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null,
      type: string,
      content: string,
      request: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type OnCreateUserSubscription = {
  onCreateUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser:  {
    __typename: "User",
    id: string,
    cognitoID: string,
    identityID: string | null,
    name: string,
    viewName: string | null,
    description: string | null,
    iconUrl: string | null,
    email: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        URL: string | null,
        tag: string | null,
        date: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreatePostSubscription = {
  onCreatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdatePostSubscription = {
  onUpdatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeletePostSubscription = {
  onDeletePost:  {
    __typename: "Post",
    id: string,
    title: string,
    URL: string | null,
    tag: string | null,
    date: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    replies:  {
      __typename: "ModelReplyConnection",
      items:  Array< {
        __typename: "Reply",
        id: string,
        postID: string,
        type: string,
        content: string,
        request: string | null,
        createdAt: string | null,
        updatedAt: string | null,
        userID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnCreateReplySubscription = {
  onCreateReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateReplySubscription = {
  onUpdateReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteReplySubscription = {
  onDeleteReply:  {
    __typename: "Reply",
    id: string,
    postID: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      URL: string | null,
      tag: string | null,
      date: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        cognitoID: string,
        identityID: string | null,
        name: string,
        viewName: string | null,
        description: string | null,
        iconUrl: string | null,
        email: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
    } | null,
    type: string,
    content: string,
    request: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      cognitoID: string,
      identityID: string | null,
      name: string,
      viewName: string | null,
      description: string | null,
      iconUrl: string | null,
      email: string,
      posts:  {
        __typename: "ModelPostConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      replies:  {
        __typename: "ModelReplyConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
  } | null,
};
